using UnityEngine;
using TMPro;
using UnityEngine.UI;
using System;

namespace Madnessnoid
{
    /// <summary>
    /// Generated by AI (partially)
    /// </summary>
    public class ResourcePopup : MonoBehaviour
    {
        public TextMeshProUGUI text;
        public Image image;
        public CanvasGroup canvasGroup;

        [Header("Animation Settings")]
        public float floatUpDistance = 50f;
        public float duration = 1.5f;

        private Vector3 startPos;
        private Vector3 endPos;

        public event Action<ResourcePopup> AnimationCompleted;

        public void Show(int amount, Sprite icon)
        {
            text.text = $"+{amount}";
            image.sprite = icon;
            startPos = transform.localPosition;
            endPos = startPos + Vector3.up * floatUpDistance;
            canvasGroup.alpha = 1f;
            StartCoroutine(Animate());
        }

        private System.Collections.IEnumerator Animate()
        {
            float time = 0f;

            while (time < duration)
            {
                float t = time / duration;
                transform.localPosition = Vector3.Lerp(startPos, endPos, t);
                canvasGroup.alpha = Mathf.Lerp(1f, 0f, t);
                time += Time.unscaledDeltaTime;
                yield return null;
            }
            gameObject.SetActive(false);

            AnimationCompleted?.Invoke(this);
        }
    }
}
